strategy:
  matrix:
    Ubuntu :
      imageName: 'ubuntu-16.04'
    High Sierra:
      imageName: 'macos-10.13'
    Mojave :
      imageName: 'macos-10.14'
    Visual Studio 2015:
      imageName: 'vs2015-win2012r2'
    Visual Studio 2017:
      imageName: 'vs2017-win2016'
    Visual Studio 2019:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)
    
variables:
    solution: '**/*.sln'    
    test: '**/EasyWakeOnLanTests.csproj'
    buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.103'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)' 

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(test)'
    arguments: '--configuration $(buildConfiguration)' 